### PR TITLE
implement find_primary_key_candidates()

### LINKED ISSUE #57: Implement find_primary_key_candidates()

### PR DESCRIPTION
**Pull request by TiaraBell**

### CODE REVIEW

**Review by claesmk — COMMENTED** [review]
I cloned your repo and tried to run your code - got this error - does demo.py run for you?
```
python demo.py
Traceback (most recent call last):
  File "ncat/tiarabell/comp410_summer2020/demo.py", line 2, in <module>
    import dfstools as dt
  File "ncat/tiarabell/comp410_summer2020/dfstools/__init__.py", line 10, in <module>
    from .src.data_tools import get_dataset_dtypes
  File "ncat/tiarabell/comp410_summer2020/dfstools/src/data_tools.py", line 74
    return relationship_dict
                           ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by TiaraBell** [comment]
It ran/runs fine for me fine.

**Comment by TiaraBell** [comment]
python demo.py
table: airlines
  col: carrier: 12: 12
found a primary key candidate
table: flights
  col: flight_id: 50557: 50557
found a primary key candidate
  col: origin: 50557: 300
  col: origin_city: 50557: 296
  col: origin_state: 50557: 52
  col: dest: 50557: 299
  col: distance_group: 50557: 11
  col: carrier: 50557: 12
  col: flight_num: 50557: 6888
  col: first_trip_logs_time: 50557: 59
table: airports
  col: dest: 299: 299
found a primary key candidate
  col: dest_city: 299: 295
  col: dest_state: 299: 52
{'airlines': {'carrier': {'dtype': 'O',
                          'key_candidate': True}},
 'airports': {'dest': {'dtype': 'O',
                       'key_candidate': True},
              'dest_city': {'key_candidate': False},
              'dest_state': {'key_candidate': False}},
 'flights': {'carrier': {'dtype': 'O',
                         'key_candidate': False},
             'dest': {'dtype': 'O',
                      'key_candidate': False},
             'distance_group': {'key_candidate': False},
             'first_trip_logs_time': {'key_candidate': False},
             'flight_id': {'dtype': 'O',
                           'key_candidate': True},
             'flight_num': {'key_candidate': False},
             'origin': {'key_candidate': False},
             'origin_city': {'key_candidate': False},
             'origin_state': {'key_candidate': False}},
 'trip_logs': {'flight_id': {'dtype': 'O'}}}

This was my output.

**Comment by claesmk** [comment]
I cloned to a PC and I see the same thing, there is definitely something wrong in your code

If you look [here](https://github.com/TiaraBell/comp410_summer2020/blob/8ef6ed0bac3d40327e51102a8542f01720f9bbcd/dfstools/src/data_tools.py#L39) the for loop is indented 3 spaces

and the return [here](https://github.com/TiaraBell/comp410_summer2020/blob/8ef6ed0bac3d40327e51102a8542f01720f9bbcd/dfstools/src/data_tools.py#L74) is indented 4 spaces, so they don't match

This causes an error in python.  Please double-check the version you are executing, I don't see how it can run unless your IDE is fixing this up automatically somehow.

**Comment by claesmk** [comment]
I fixed the indent problem and when I ran your code it revealed a bug in find_related_cols_by_content() which I [fixed](https://github.com/NCATComp410/comp410_summer2020/commit/4e95a1c3eb330cd6073868a744f970bcf7f81898) so I think you need to pull the latest into your fork, fix your indent, then you'll be OK

**Review by claesmk — APPROVED** [review]
OK this looks good.  I'm going to approve the pull request and will let you know if there are any issues

**Pull request merged**
