### PR TITLE
Merging Issue #43

### LINKED ISSUE #43: Make absolute paths safe for PC users
Fix hardcoded paths that are not cross-platform safe, for example
```
dataframe_dict = {'airlines': pd.read_csv('data/airlines/airlines.csv'),
                      'flights': pd.read_csv('data/flights/flights.csv'),
                      'airports': pd.read_csv('data/airports/airports.csv')}
```
Will only work on linux/Mac and will fail on a pc

### PR DESCRIPTION
**Pull request by claesmk**
Issue https://github.com/NCATComp410/comp410_summer2020/issues/43

### CODE REVIEW

**Comment by claesmk** [comment]
```
---------- coverage: platform darwin, python 3.8.3-final-0 -----------
Name                                        Stmts   Miss  Cover
---------------------------------------------------------------
dfstools/__init__.py                            7      0   100%
dfstools/src/csv_tools.py                       6      0   100%
dfstools/src/data_tools.py                     18      0   100%
dfstools/src/relationship_tools.py             40      3    92%
dfstools/tests/__init__.py                      0      0   100%
dfstools/tests/test_console.py                 12      1    92%
dfstools/tests/test_csv_tools.py               18      1    94%
dfstools/tests/test_data_tools.py              13      1    92%
dfstools/tests/test_relationship_tools.py      25      1    96%
---------------------------------------------------------------
TOTAL                                         139      7    95%
```

**Comment by claesmk** [comment]
@dmeyer3691 I think my path-safe code was actually not needed because pandas seems to handle it OK, never the less I decided to push this because I think it's a good reminder to write code that is platform safe.  Let me know if you have any issues, otherwise please approve and complete the merge. 

@skerr92 I made a couple of changes to improve your solutions. One thing I wanted to clarify.  Python is basically a call-by-object language
```
def search_by_name(df_list, rel_dict)
```
Your function takes two mutable objects as parameters.  So, if you modify rel_dict in your function (which you do) those modifications are available to the caller:
```
    if relationship_dict is None:
        relationship_dict = {}

    # relationship_dict is now an empty dict 

    search_by_name(dataframe_list, relationship_dict)

    # relationship_dict now has the modifications made by search_by_name()
```

But what if I changed this a bit, lets say I handle the None case in search_by_name()
```
def search_by_name(df_list, rel_dict=None)

...

    search_by_name(dataframe_list)

    # relationship_dict now does not have the modifications because it didn't exist yet
```

So this is why it's better to return the rel_dict in search_by_name(). In the None case, it guarantees it will work, in the case where you actually passed a mutable object, the extra assignment doesn't actually do anything but makes what's happening clearer. 

So, during the next sprint, we'll modify search_by_name() to return rel_dict.

**Review by dmeyer3691 — APPROVED** [review]
also showing good test coverage and passing. changes make sense, let's not forget the change to search_by_name in next sprint

---------- coverage: platform darwin, python 3.8.3-final-0 -----------
Name                               Stmts   Miss  Cover
------------------------------------------------------
__init__.py                            7      0   100%
src/csv_tools.py                       6      0   100%
src/data_tools.py                     18      0   100%
src/relationship_tools.py             40      3    92%
tests/__init__.py                      0      0   100%
tests/test_console.py                 12      1    92%
tests/test_csv_tools.py               18      1    94%
tests/test_data_tools.py              13      1    92%
tests/test_relationship_tools.py      25      1    96%
------------------------------------------------------
TOTAL                                139      7    95%

**Comment by dmeyer3691** [comment]
issue #43 is resolved with this merge

**Pull request merged**
