### PR TITLE
Implement get_dataset_dtypes() #58

### LINKED ISSUE #58: Implement get_dataset_dtypes()

### PR DESCRIPTION
**Pull request by vjmerritt**
https://github.com/NCATComp410/comp410_summer2020/issues/58

### CODE REVIEW

**Comment by claesmk** [comment]
I can make some time later today either at 5pm or after the team demos are over (around 7pm) do either of those times work for you?

**Comment by vjmerritt** [comment]
Is 8 pm okay?

**Comment by vjmerritt** [comment]
I can do 5 pm today

**Review by claesmk — APPROVED** [review]
Looks good thanks for working on this today

**Pull request merged**
